server:
  port: 8090
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8


spring:
  datasource:
    url : jdbc:mysql://192.168.0.69:3306/demo
    username : root
    password : asd!123!
    driverClassName : com.mysql.jdbc.Driver
    thymeleaf:
    cache: false


