export const SET_TOKEN = 'SET_TOKEN'
export const SET_EXPIRES = 'SET_EXPIRES'
export const SET_ROLES = 'SET_ROLES'
export const SET_ROUTERS = 'SET_ROUTERS'
export const SET_AVATAR = 'SET_AVATAR'
export const SET_NAME = 'SET_NAME'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const ADD_VISITED_VIEWS = 'ADD_VISITED_VIEWS'
export const DEL_VISITED_VIEWS = 'DEL_VISITED_VIEWS'